*&---------------------------------------------------------------------*
*&  Include           ZGOODISSUE_UPLOAD
*&---------------------------------------------------------------------*

AT SELECTION-SCREEN ON VALUE-REQUEST FOR P_FILE.
  CALL FUNCTION 'F4_FILENAME'
    EXPORTING
      FIELD_NAME = P_FILE "Here file_LOC is the text Element name on Screen.
    IMPORTING
      FILE_NAME  = FILE_PATH.
  P_FILE = FILE_PATH .

START-OF-SELECTION .

  CALL FUNCTION 'ALSM_EXCEL_TO_INTERNAL_TABLE'
    EXPORTING
      FILENAME                = FILE_PATH
      I_BEGIN_COL             = 1
      I_BEGIN_ROW             = 2
      I_END_COL               = 8
      I_END_ROW               = 102
    TABLES
      INTERN                  = IT_FILE
    EXCEPTIONS
      INCONSISTENT_PARAMETERS = 1
      UPLOAD_OLE              = 2
      OTHERS                  = 3.
  IF SY-SUBRC <> 0.
* Implement suitable error handling here
  ENDIF.

  IF SY-UNAME = 'H.KORTAM' .
    BREAK-POINT .
  ENDIF.

  LOOP AT IT_FILE .
    CASE IT_FILE-COL.
      WHEN '0001' .
        MOVE IT_FILE-VALUE TO WA_UPLD-BLDAT.
      WHEN '0002' .
        MOVE IT_FILE-VALUE TO WA_UPLD-BUDAT.
      WHEN '0003' .
        MOVE IT_FILE-VALUE TO WA_UPLD-BKTXT.
      WHEN '0004' .
        MOVE IT_FILE-VALUE TO WA_UPLD-RSNUM.
      WHEN '0005' .
        MOVE IT_FILE-VALUE TO WA_UPLD-RSPOS.
      WHEN '0006' .
        MOVE IT_FILE-VALUE TO WA_UPLD-LGORT .
      WHEN '0007' .
        MOVE IT_FILE-VALUE TO WA_UPLD-MENGE.
      WHEN '0008' .
        MOVE IT_FILE-VALUE TO WA_UPLD-SGTXT.
    ENDCASE .
    AT END OF ROW.
      APPEND WA_UPLD TO IT_UPLD.
      CLEAR WA_UPLD.
    ENDAT.
*       APPEND TBU_UPLOAD.
  ENDLOOP.

  DESCRIBE TABLE IT_UPLD LINES NUM .
  IF NUM > 100.
    concatenate ' لقد تجاوزت عدد الاسطر المسموح بها '  'ال100 سطر'  into RETURNMSG SEPARATED BY space .
    MESSAGE RETURNMSG  TYPE 'E' .
  ENDIF.

  READ TABLE IT_UPLD INTO WA_UPLD INDEX 1 . """ ALL RECORDS SHOULD SHARE THE FIRST RECORD'S HEADER DATA
  IF SY-SUBRC = 0 .
    CONCATENATE WA_UPLD-BLDAT+6(4) WA_UPLD-BLDAT+3(2) WA_UPLD-BLDAT(2) INTO GOODSMVT_HEADER-PSTNG_DATE .
    CONCATENATE WA_UPLD-BUDAT+6(4) WA_UPLD-BUDAT+3(2) WA_UPLD-BUDAT(2) INTO GOODSMVT_HEADER-DOC_DATE .
    GOODSMVT_HEADER-HEADER_TXT = WA_UPLD-BKTXT .
  ENDIF.

  CLEAR : WA_UPLD .
  LOOP AT IT_UPLD INTO WA_UPLD .
    GOODSMVT_ITEM-RESERV_NO = WA_UPLD-RSNUM .
    GOODSMVT_ITEM-RES_ITEM = WA_UPLD-RSPOS .
    GOODSMVT_ITEM-STGE_LOC = WA_UPLD-LGORT .
    GOODSMVT_ITEM-QUANTITY = WA_UPLD-MENGE .
    GOODSMVT_ITEM-ENTRY_QNT = WA_UPLD-MENGE .
    GOODSMVT_ITEM-ITEM_TEXT = WA_UPLD-SGTXT .
    GOODSMVT_ITEM-MOVE_TYPE = '281' .
    APPEND GOODSMVT_ITEM .

  ENDLOOP.


  CALL FUNCTION 'BAPI_GOODSMVT_CREATE'
    EXPORTING
      GOODSMVT_HEADER  = GOODSMVT_HEADER
      GOODSMVT_CODE    = '03'
*     TESTRUN          = ' '
*     GOODSMVT_REF_EWM =
    IMPORTING
*     GOODSMVT_HEADRET =
      MATERIALDOCUMENT = MATERIALDOCUMENT
*     MATDOCUMENTYEAR  =
    TABLES
      GOODSMVT_ITEM    = GOODSMVT_ITEM
*     GOODSMVT_SERIALNUMBER         =
      RETURN           = RETURN
*     GOODSMVT_SERV_PART_DATA       =
*     EXTENSIONIN      =
    .


  CLEAR NUM .
  READ TABLE RETURN WITH KEY TYPE = 'E' .
  IF SY-SUBRC = 0 .
    LOOP AT RETURN WHERE TYPE = 'E'.
      NUM = RETURN-ROW + 1.
      WRITE : 'Error in Excel Line' , NUM , RETURN-MESSAGE.
      CLEAR NUM .
    ENDLOOP.
  ELSE.
    COMMIT WORK .
    CONCATENATE 'Document Uploaded successfully, material document: ' MATERIALDOCUMENT  INTO RETURNMSG SEPARATED BY SPACE .
*    MESSAGE RETURNMSG  TYPE 'I' .
    write : RETURNMSG .
  ENDIF.

  clear p_file .
