*&---------------------------------------------------------------------*
*&  Include           ZGOODISSUE_TOP
*&---------------------------------------------------------------------*

TYPES : BEGIN OF ISSUE ,
          BLDAT TYPE CHAR10,
          BUDAT TYPE CHAR10,
          BKTXT TYPE BKTXT,
          RSNUM TYPE RSNUM,
          RSPOS TYPE RSPOS,
          LGORT TYPE LGORT_D,
          MENGE TYPE MENGE_D,
          SGTXT TYPE SGTXT,
        END OF ISSUE .

DATA : IT_UPLD TYPE TABLE OF ISSUE,
       WA_UPLD TYPE ISSUE.

DATA :
  GOODSMVT_ITEM         TYPE TABLE OF   BAPI2017_GM_ITEM_CREATE WITH HEADER LINE,
  GOODSMVT_SERIALNUMBER TYPE TABLE OF   BAPI2017_GM_SERIALNUMBER,
  RETURN                TYPE TABLE OF   BAPIRET2 WITH HEADER LINE.

DATA :
  GOODSMVT_HEADER  LIKE  BAPI2017_GM_HEAD_01,
  GOODSMVT_CODE    LIKE  BAPI2017_GM_CODE,
  MATERIALDOCUMENT TYPE  BAPI2017_GM_HEAD_RET-MAT_DOC.

DATA : RETURNMSG TYPE CHAR100 .

DATA : IT_FILE  LIKE ALSMEX_TABLINE OCCURS 0 WITH HEADER LINE.

DATA FILE_PATH LIKE  RLGRAP-FILENAME.

DATA : NUM TYPE I.
